name = "PlautBeamColumnElement"
uuid = "a45b55a3-f080-4392-acba-796e05a72a03"
version = "0.1.0"
authors = ["Cris Moen <cris.moen@runtosolve.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"

[compat]
LinearAlgebra = "1"
NonlinearSolve = "3, 4"
julia = "1.10"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LinearAlgebra"]
